- name: Build compose env file list
  ansible.builtin.set_fact:
    compose_env_files: "{{ compose_env_files_base + compose_env_files_extra }}"

- name: Bring up data stack
  ansible.builtin.shell: >
    docker compose -p {{ compose_project_data }}
    {% for env_file in compose_env_files %} --env-file {{ env_file }}{% endfor %}
    -f {{ data_compose_file }} up -d{% if compose_build %} --build{% endif %}
  args:
    chdir: "{{ repo_path }}"
