apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: ${DATA_NODE_IP}:${CLUSTER_DATA_DB_HOST_PORT}
    user: ${POSTGRES_READONLY_USER}
    secureJsonData:
      password: ${POSTGRES_READONLY_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: ${DB_SSLMODE}
      postgresVersion: 1600
      timescaledb: true
