# docker/monitoring/prometheus.yml
# NOTE: Update target IPs/ports when moving to multiple machines.

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "django"
    scheme: https
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:18443"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["host.docker.internal:9187"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]
