# docker/monitoring/prometheus.yml
# NOTE: Update target IPs/ports when moving to multiple machines.

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "django"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.0.127:28000"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["192.168.0.127:9187"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["192.168.0.127:9100"]
