mode: single
env_file: docker/cluster/.env.cluster
template: docker/cluster/.env.cluster.example
prometheus: docker/monitoring/prometheus.yml
update_prometheus: true
backup_env: true

single:
  ip: 192.168.0.127
  container_ip: host.docker.internal
  host_gateway: host-gateway
  app_https_port: 18443
  primary_port: 25432
  replica_base_port: 25433
  replica_count: 2
  replicas: []

multi:
  data_ip: 192.168.0.10
  control_ip: 192.168.0.11
  app_ip: 192.168.0.12
  app_https_port: 443
  allow_single_ip: false
  primary_host: 192.168.0.10:5432
  primary_port: 5432
  replicas:
    - 192.168.0.13:5432
    - 192.168.0.14:5432
